# Generated by Django 5.2.1 on 2025-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=100)),
                ('emp_first_name', models.CharField(max_length=100)),
                ('emp_last_name', models.CharField(max_length=100)),
                ('emp_city', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('cmp_name', models.CharField(max_length=100)),
            ],
        ),
    ]
