# Generated by Django 5.2.1 on 2025-06-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Category_description', models.TextField(max_length=100)),
                ('Category_image', models.ImageField(upload_to='Category_image')),
            ],
        ),
    ]
