# Generated by Django 5.2.1 on 2025-06-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Product',
        ),
    ]
