# Generated by Django 5.2.1 on 2025-07-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='full_name',
        ),
    ]
