# Generated by Django 5.2.1 on 2025-07-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
