# Generated by Django 5.2.1 on 2025-07-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
