# Generated by Django 5.2.1 on 2025-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('query', models.CharField(choices=[('refund', 'Refund'), ('return', 'Return'), ('call_me', 'Call Me'), ('delivery_related', 'Delivery Related')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
