# Generated by Django 5.2.1 on 2025-07-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
